[Tizen] Add "--no-parallel" when run gyp_xwalk
Build Tizen on chroot does not mount a /dev/shm, this will cause
gyp_xwalk fail to run with below python error:

    File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 49, in
  __init__
      sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
  OSError: [Errno 38] Function not implemented

Check details on
http://stackoverflow.com/questions/6033599/oserror-38-errno-38-with-multiprocessing

Simply add "--no-parallel" will resolve this issue.